version: '3'

services:
  django:
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    expose:
      - 8000
    volumes:
      - static_data:/app/staticfiles
      - media:/app/media
    restart: unless-stopped
    command: ["bash","./start.sh"]

  postgres:
    image: postgres:15
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      start_period: 1s
      retries: 5

  nginx:
    image: nginx:latest
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
      - static_data:/var/www/static
      - media:/var/www/media

volumes:
  static_data:
  media: