# Generated by Django 4.1.5 on 2023-01-14 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import requesting.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема поручения')),
                ('text', models.TextField(max_length=200, verbose_name='Текст поручения')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='Уложитесь в 50 символов', max_length=50, verbose_name='Тема')),
                ('requesting_message', models.TextField(max_length=200, verbose_name='Текст сообщения')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время подачи заявки')),
                ('active', models.BooleanField(default=True, verbose_name='Активные')),
                ('location', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кабинет')),
                ('state', models.CharField(default='Ожидает', max_length=20, verbose_name='Состояние')),
                ('deadline', models.DateField(validators=[requesting.validators.validate_deadline], verbose_name='Выполнить до')),
                ('priority', models.CharField(choices=[('1', 'Нейтрально'), ('2', 'Средне'), ('3', 'Срочно')], default='Нейтрально', max_length=2, verbose_name='Приоритет')),
                ('implementer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('soimplementor', models.ManyToManyField(related_name='subimplemetor', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
