# Generated by Django 4.1.5 on 2023-01-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_give_tasks', 'Может поурчать задания'),), 'verbose_name': 'Поручение', 'verbose_name_plural': 'Поручения'},
        ),
    ]
