# Generated by Django 4.1.5 on 2023-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Вложение'),
        ),
    ]
