# Generated by Django 4.1.5 on 2023-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0002_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда выполненно'),
        ),
    ]
