# Generated by Django 4.1.5 on 2023-01-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0002_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
    ]
