# Generated by Django 4.1.5 on 2023-01-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0003_remove_task_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_give_tasks', 'Может получать задания'),), 'verbose_name': 'Поручение', 'verbose_name_plural': 'Поручения'},
        ),
    ]
