# Generated by Django 4.2.1 on 2023-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0004_formmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Вложение'),
        ),
    ]
