# Generated by Django 4.1.5 on 2023-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='theme',
            field=models.CharField(help_text='Уложитесь в 15 символов', max_length=15, verbose_name='Тема'),
        ),
    ]
