# Generated by Django 4.2.1 on 2023-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0005_alter_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='formmessage',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Сообщение'),
        ),
    ]
