# Generated by Django 4.1.5 on 2023-01-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0005_alter_form_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='theme',
            field=models.CharField(help_text='Уложитесь в 30 символов', max_length=30, verbose_name='Тема'),
        ),
    ]
