# Generated by Django 4.2.1 on 2023-05-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0006_alter_formmessage_image_alter_formmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formmessage',
            options={'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='form',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requesting.formmessage', verbose_name='Сообщения'),
        ),
    ]
