# Generated by Django 4.0.6 on 2023-01-16 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0006_alter_form_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='location',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='form',
            name='priority',
            field=models.CharField(choices=[('1', 'Низкий'), ('2', 'Средний'), ('3', 'Срочный')], default='Нейтрально', max_length=2, verbose_name='Приоритет'),
        ),
    ]
