# Generated by Django 4.0.6 on 2023-01-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0007_alter_form_location_alter_form_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='priority',
            field=models.CharField(choices=[('1', 'Низкий'), ('2', 'Средний'), ('3', 'Срочный')], default='Низкий', max_length=2, verbose_name='Приоритет'),
        ),
    ]
