# Generated by Django 4.2.1 on 2023-05-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0007_alter_formmessage_options_form_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_messages', to='requesting.formmessage', verbose_name='Сообщения'),
        ),
    ]
