# Generated by Django 4.0.6 on 2023-03-14 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0008_alter_form_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='done_at',
            field=models.DateTimeField(null=True, verbose_name='Когда выполненно'),
        ),
        migrations.AlterField(
            model_name='form',
            name='location',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='form',
            name='priority',
            field=models.CharField(choices=[('1', 'Нейтрально'), ('2', 'Средне'), ('3', 'Срочно')], default='Нейтрально', max_length=2, verbose_name='Приоритет'),
        ),
    ]
