# Generated by Django 4.2.1 on 2023-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0008_alter_form_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='messages',
        ),
        migrations.AddField(
            model_name='form',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_messages', to='requesting.formmessage', verbose_name='Сообщения'),
        ),
    ]
