# Generated by Django 4.2.1 on 2023-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0009_remove_form_messages_form_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='form',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='requesting.formmessage', verbose_name='Сообщения'),
        ),
    ]
