# Generated by Django 4.2.1 on 2023-05-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0010_form_created_at_alter_form_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP Адрес'),
        ),
    ]
