# Generated by Django 4.2.1 on 2023-05-31 16:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesting', '0011_alter_customuser_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
